title: 우영의 일기
logo: /assets/img/logo.png
description: This is my open diary which is writen in Korean to practice my Korean writing skills
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
